print("="*40)
print("La aventura a empezado")
print("="*40)
Print("Un anciano te pregunta tu nombre")
nombre=input("Di tu nombre")
print("Hola",nombre)
print("")
print("Quien quieres ser")
print("Guerrero    30 de vida y 10 de ataque")
print("Ladron    20 de vida y 20 de ataque ")
print("Mago     27 de vida y 13 de ataque  ")
